Movie list
Magnificent-12/movie-app pull request #23
Opened 2022-02-26 16:42 UTC by RejzovicEmir

# Description

Created a Movie List that filters data based on user input or movie genre.
It uses movie card as its component  

Task # ([Create movie list](https://app.clickup.com/t/269a193))

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-02-26 16:50 UTC, zlayabekrija requested changes
Looks cool, please address a few comments we have made.
If you need any help, please reach out via Slack.

Happy coding.

2022-02-26 16:50 UTC, zlayabekrija commented on src/Pages/Genre.js
> +          movieGenre={movie.genres.map((genre, index) => {
Please take this logic in reusable function, also if the movie genres is an array, the rather use the join method.
Example
const getGenres = (genres)=>genres.join(", ")

2022-02-26 16:50 UTC, zlayabekrija commented on src/Pages/Genre.js
> +          movieFavorite={false}
Why is this value hard coded?

2022-02-26 16:55 UTC, AmerMekic commented on src/Pages/Genre.js
> +          movieFavorite={false}
movieFavorite is hard coded because we made the movieList before addToFavorites, it will be a prop when we make the localstorage favorites list

2022-02-26 16:55 UTC, AmerMekic commented on src/Pages/Genre.js
> +          movieGenre={movie.genres.map((genre, index) => {
I will change that now

2022-02-26 17:30 UTC, AmerMekic commented on src/Pages/Genre.js
> +          movieGenre={movie.genres.map((genre, index) => {
Finished

2022-02-27 11:42 UTC, zlayabekrija approved these changes

2022-02-27 12:13 UTC, AmerMekic approved these changes

2022-02-27 12:13 UTC, merged