fixing mistakes
Magnificent-12/movie-app pull request #24
Opened 2022-02-27 11:42 UTC by Dzastinche

# Description
there was a simple mistake about favorite actions, am just fixed that...

2022-02-27 11:44 UTC, zlayabekrija requested changes

2022-02-27 11:44 UTC, zlayabekrija commented on src/redux/redux-reducers/userstore.jsx
> +  reducers: {},
let add at least one reducer, for example ```setUser```

2022-02-28 00:37 UTC, zlayabekrija approved these changes
Good work :100:

2022-02-28 01:08 UTC, AmerMekic approved these changes

2022-02-28 01:09 UTC, merged